# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
=begin
	ProductosMercado.create(sku: 1,nombre: 'Pollo',tipo: 'Materia prima',grupo: 7,unidades: 'Kg',costoProduccion: 892,loteProduccion: 300,tiempoProduccion: 2.041)
	ProductosMercado.create(sku: 2,nombre: 'Huevo',tipo: 'Materia prima',grupo: 2,unidades: 'Un',costoProduccion: 513,loteProduccion: 150,tiempoProduccion: 3.736)
	ProductosMercado.create(sku: 3,nombre: 'Maíz',tipo: 'Materia prima',grupo: 10,unidades: 'Kg',costoProduccion: 1468,loteProduccion: 30,tiempoProduccion: 3.532)
	ProductosMercado.create(sku: 4,nombre: 'Aceite de Maravilla',tipo: 'Producto procesado',grupo: 11,unidades: 'Lts',costoProduccion: 863,loteProduccion: 200,tiempoProduccion: 3.026)
	ProductosMercado.create(sku: 5,nombre: 'Yogur ',tipo: 'Producto procesado',grupo: 11,unidades: 'Lts',costoProduccion: 2197,loteProduccion: 600,tiempoProduccion: 3.526)
	ProductosMercado.create(sku: 6,nombre: 'Crema',tipo: 'Producto procesado',grupo: 3,unidades: 'Lts',costoProduccion: 2402,loteProduccion: 30,tiempoProduccion: 0.979)
	ProductosMercado.create(sku: 7,nombre: 'Leche',tipo: 'Materia prima',grupo: 12,unidades: 'Lts',costoProduccion: 941,loteProduccion: 1000,tiempoProduccion: 4.248)
	ProductosMercado.create(sku: 8,nombre: 'Trigo',tipo: 'Materia prima',grupo: 3,unidades: 'Kg',costoProduccion: 1313,loteProduccion: 100,tiempoProduccion: 0.784)
	ProductosMercado.create(sku: 9,nombre: 'Carne',tipo: 'Materia prima',grupo: 10,unidades: 'Kg',costoProduccion: 1397,loteProduccion: 620,tiempoProduccion: 4.279)
	ProductosMercado.create(sku: 10,nombre: 'Pan Marraqueta',tipo: 'Producto procesado',grupo: 7,unidades: 'Kg',costoProduccion: 2572,loteProduccion: 900,tiempoProduccion: 3.677)
	ProductosMercado.create(sku: 11,nombre: 'Margarina ',tipo: 'Producto procesado',grupo: 4,unidades: 'Kg',costoProduccion: 1839,loteProduccion: 900,tiempoProduccion: 4.118)
	ProductosMercado.create(sku: 12,nombre: 'Cereal Avena ',tipo: 'Producto procesado',grupo: 2,unidades: 'Kg',costoProduccion: 2581,loteProduccion: 400,tiempoProduccion: 3.056)
	ProductosMercado.create(sku: 13,nombre: 'Arroz',tipo: 'Materia prima',grupo: 6,unidades: 'Kg',costoProduccion: 1286,loteProduccion: 1000,tiempoProduccion: 2.89)
	ProductosMercado.create(sku: 14,nombre: 'Cebada',tipo: 'Materia prima',grupo: 3,unidades: 'Kg',costoProduccion: 696,loteProduccion: 1750,tiempoProduccion: 1.355)
	ProductosMercado.create(sku: 15,nombre: 'Avena',tipo: 'Materia prima',grupo: 12,unidades: 'Kg',costoProduccion: 969,loteProduccion: 480,tiempoProduccion: 3.965)
	ProductosMercado.create(sku: 16,nombre: 'Pasta de Trigo ',tipo: 'Producto procesado',grupo: 4,unidades: 'Kg',costoProduccion: 2292,loteProduccion: 1000,tiempoProduccion: 2.992)
	ProductosMercado.create(sku: 17,nombre: 'Cereal Arroz ',tipo: 'Producto procesado',grupo: 6,unidades: 'Kg',costoProduccion: 2184,loteProduccion: 1000,tiempoProduccion: 2.052)
	ProductosMercado.create(sku: 18,nombre: 'Pastel ',tipo: 'Producto procesado',grupo: 8,unidades: 'Un',costoProduccion: 2140,loteProduccion: 200,tiempoProduccion: 0.941)
	ProductosMercado.create(sku: 19,nombre: 'Sémola',tipo: 'Materia prima',grupo: 1,unidades: 'Kg',costoProduccion: 1428,loteProduccion: 1420,tiempoProduccion: 4.033)
	ProductosMercado.create(sku: 20,nombre: 'Cacao',tipo: 'Materia prima',grupo: 9,unidades: 'Kg',costoProduccion: 1280,loteProduccion: 60,tiempoProduccion: 4.101)
	ProductosMercado.create(sku: 21,nombre: 'Algodón',tipo: 'Materia prima',grupo: 2,unidades: 'Kg',costoProduccion: 1272,loteProduccion: 100,tiempoProduccion: 1.157)
	ProductosMercado.create(sku: 22,nombre: 'Mantequilla ',tipo: 'Producto procesado',grupo: 11,unidades: 'Kg',costoProduccion: 1891,loteProduccion: 400,tiempoProduccion: 1.951)
	ProductosMercado.create(sku: 23,nombre: 'Harina',tipo: 'Producto procesado',grupo: 7,unidades: 'Kg',costoProduccion: 1534,loteProduccion: 300,tiempoProduccion: 3.95)
	ProductosMercado.create(sku: 24,nombre: 'Tela de Seda ',tipo: 'Producto procesado',grupo: 8,unidades: 'Mts',costoProduccion: 1442,loteProduccion: 400,tiempoProduccion: 0.695)
	ProductosMercado.create(sku: 25,nombre: 'Azúcar',tipo: 'Materia prima',grupo: 6,unidades: 'Kg',costoProduccion: 782,loteProduccion: 560,tiempoProduccion: 1.515)
	ProductosMercado.create(sku: 26,nombre: 'Sal',tipo: 'Materia prima',grupo: 8,unidades: 'Kg',costoProduccion: 753,loteProduccion: 144,tiempoProduccion: 0.784)
	ProductosMercado.create(sku: 27,nombre: 'Levadura',tipo: 'Materia prima',grupo: 1,unidades: 'Kg',costoProduccion: 1084,loteProduccion: 620,tiempoProduccion: 2.717)
	ProductosMercado.create(sku: 28,nombre: 'Tela de Lino ',tipo: 'Producto procesado',grupo: 2,unidades: 'Mts',costoProduccion: 1138,loteProduccion: 500,tiempoProduccion: 3.754)
	ProductosMercado.create(sku: 29,nombre: 'Tela de Lana ',tipo: 'Producto procesado',grupo: 10,unidades: 'Mts',costoProduccion: 1868,loteProduccion: 400,tiempoProduccion: 1.961)
	ProductosMercado.create(sku: 30,nombre: 'Tela de Algodón ',tipo: 'Producto procesado',grupo: 12,unidades: 'Mts',costoProduccion: 1698,loteProduccion: 500,tiempoProduccion: 3.865)
	ProductosMercado.create(sku: 31,nombre: 'Lana',tipo: 'Materia prima',grupo: 3,unidades: 'Mts',costoProduccion: 1434,loteProduccion: 960,tiempoProduccion: 3.449)
	ProductosMercado.create(sku: 32,nombre: 'Cuero',tipo: 'Materia prima',grupo: 2,unidades: 'Un',costoProduccion: 996,loteProduccion: 230,tiempoProduccion: 2.834)
	ProductosMercado.create(sku: 33,nombre: 'Seda',tipo: 'Materia prima',grupo: 5,unidades: 'Kg',costoProduccion: 834,loteProduccion: 90,tiempoProduccion: 0.711)
	ProductosMercado.create(sku: 34,nombre: 'Cerveza ',tipo: 'Producto procesado',grupo: 12,unidades: 'Lts',costoProduccion: 1294,loteProduccion: 700,tiempoProduccion: 1.505)
	ProductosMercado.create(sku: 35,nombre: 'Tequila ',tipo: 'Producto procesado',grupo: 10,unidades: 'Lts',costoProduccion: 1435,loteProduccion: 500,tiempoProduccion: 1.16)
	ProductosMercado.create(sku: 36,nombre: 'Papel ',tipo: 'Producto procesado',grupo: 11,unidades: 'Mts',costoProduccion: 1786,loteProduccion: 100,tiempoProduccion: 3.918)
	ProductosMercado.create(sku: 37,nombre: 'Lino',tipo: 'Materia prima',grupo: 8,unidades: 'Mts',costoProduccion: 764,loteProduccion: 1200,tiempoProduccion: 2.797)
	ProductosMercado.create(sku: 38,nombre: 'Semillas Maravilla',tipo: 'Materia prima',grupo: 4,unidades: 'Kg',costoProduccion: 1201,loteProduccion: 30,tiempoProduccion: 1.805)
	ProductosMercado.create(sku: 39,nombre: 'Uva',tipo: 'Materia prima',grupo: 7,unidades: 'Kg',costoProduccion: 889,loteProduccion: 250,tiempoProduccion: 3.753)
	ProductosMercado.create(sku: 40,nombre: 'Queso ',tipo: 'Producto procesado',grupo: 1,unidades: 'Kg',costoProduccion: 2324,loteProduccion: 900,tiempoProduccion: 3.589)
	ProductosMercado.create(sku: 41,nombre: 'Suero de Leche',tipo: 'Producto procesado',grupo: 10,unidades: 'Lts',costoProduccion: 1407,loteProduccion: 200,tiempoProduccion: 3.983)
	ProductosMercado.create(sku: 42,nombre: 'Cereal Maíz',tipo: 'Producto procesado',grupo: 5,unidades: 'Kg',costoProduccion: 1949,loteProduccion: 200,tiempoProduccion: 1.459)
	ProductosMercado.create(sku: 43,nombre: 'Madera',tipo: 'Materia prima',grupo: 11,unidades: 'Mts3',costoProduccion: 1197,loteProduccion: 1000,tiempoProduccion: 1.27)
	ProductosMercado.create(sku: 44,nombre: 'Agave',tipo: 'Materia prima',grupo: 4,unidades: 'Kg',costoProduccion: 1091,loteProduccion: 50,tiempoProduccion: 2.56)
	ProductosMercado.create(sku: 45,nombre: 'Celulosa',tipo: 'Materia prima',grupo: 1,unidades: 'Kg',costoProduccion: 1500,loteProduccion: 800,tiempoProduccion: 0.759)
	ProductosMercado.create(sku: 46,nombre: 'Chocolate',tipo: 'Producto procesado',grupo: 9,unidades: 'Kg',costoProduccion: 2372,loteProduccion: 800,tiempoProduccion: 1.205)
	ProductosMercado.create(sku: 47,nombre: 'Vino ',tipo: 'Producto procesado',grupo: 1,unidades: 'Lts',costoProduccion: 1921,loteProduccion: 1000,tiempoProduccion: 0.677)
	ProductosMercado.create(sku: 48,nombre: 'Pasta de Sémola ',tipo: 'Producto procesado',grupo: 9,unidades: 'Kg',costoProduccion: 1652,loteProduccion: 500,tiempoProduccion: 2.47)
	ProductosMercado.create(sku: 49,nombre: 'Leche Descremada',tipo: 'Producto procesado',grupo: 3,unidades: 'Lts',costoProduccion: 1459,loteProduccion: 200,tiempoProduccion: 4.281)
	ProductosMercado.create(sku: 50,nombre: 'Arroz con Leche',tipo: 'Producto procesado',grupo: 5,unidades: 'Kg',costoProduccion: 1940,loteProduccion: 350,tiempoProduccion: 4.058)
	ProductosMercado.create(sku: 51,nombre: 'Pan Hallulla',tipo: 'Producto procesado',grupo: 12,unidades: 'Kg',costoProduccion: 2153,loteProduccion: 600,tiempoProduccion: 1.658)
	ProductosMercado.create(sku: 52,nombre: 'Harina Integral',tipo: 'Materia prima',grupo: 5,unidades: 'Kg',costoProduccion: 1466,loteProduccion: 890,tiempoProduccion: 2.13)
	ProductosMercado.create(sku: 53,nombre: 'Pan Integral',tipo: 'Producto procesado',grupo: 6,unidades: 'Kg',costoProduccion: 2632,loteProduccion: 620,tiempoProduccion: 3.89)
	ProductosMercado.create(sku: 54,nombre: 'Hamburguesas',tipo: 'Producto procesado',grupo: 10,unidades: 'Kg',costoProduccion: 2190,loteProduccion: 1800,tiempoProduccion: 4.012)
	ProductosMercado.create(sku: 55,nombre: 'Galletas Integrales',tipo: 'Producto procesado',grupo: 3,unidades: 'Kg',costoProduccion: 2284,loteProduccion: 950,tiempoProduccion: 3.955)
	ProductosMercado.create(sku: 56,nombre: 'Hamburguesas de Pollo',tipo: 'Producto procesado',grupo: 9,unidades: 'Kg',costoProduccion: 2271,loteProduccion: 620,tiempoProduccion: 2.01)
=end

	FormulasProducto.create(skuProducto: 4,nombreProducto: 'Aceite de Maravilla',lote: 200,unidadProducto: 'Lts',skuIngrediente: 38,nombreIngrediente: 'Semillas Maravilla',requerimiento: 190,unidadIngrediente: 'Kg',precioIngrediente: 1513)
	FormulasProducto.create(skuProducto: 5,nombreProducto: 'Yogur ',lote: 600,unidadProducto: 'Lts',skuIngrediente: 41,nombreIngrediente: 'Suero de Leche',requerimiento: 194,unidadIngrediente: 'Lts',precioIngrediente: 3148)
	FormulasProducto.create(skuProducto: 5,nombreProducto: 'Yogur ',lote: 600,unidadProducto: 'Lts',skuIngrediente: 6,nombreIngrediente: 'Crema',requerimiento: 228,unidadIngrediente: 'Lts',precioIngrediente: 9678)
	FormulasProducto.create(skuProducto: 5,nombreProducto: 'Yogur ',lote: 600,unidadProducto: 'Lts',skuIngrediente: 49,nombreIngrediente: 'Leche Descremada',requerimiento: 228,unidadIngrediente: 'Lts',precioIngrediente: 3568)
	FormulasProducto.create(skuProducto: 6,nombreProducto: 'Crema',lote: 30,unidadProducto: 'Lts',skuIngrediente: 49,nombreIngrediente: 'Leche Descremada',requerimiento: 100,unidadIngrediente: 'Lts',precioIngrediente: 3568)
	FormulasProducto.create(skuProducto: 6,nombreProducto: 'Crema',lote: 30,unidadProducto: 'Lts',skuIngrediente: 7,nombreIngrediente: 'Leche',requerimiento: 300,unidadIngrediente: 'Lts',precioIngrediente: 1307)
	FormulasProducto.create(skuProducto: 10,nombreProducto: 'Pan Marraqueta',lote: 900,unidadProducto: 'Kg',skuIngrediente: 23,nombreIngrediente: 'Harina',requerimiento: 342,unidadIngrediente: 'Kg',precioIngrediente: 4294)
	FormulasProducto.create(skuProducto: 10,nombreProducto: 'Pan Marraqueta',lote: 900,unidadProducto: 'Kg',skuIngrediente: 26,nombreIngrediente: 'Sal',requerimiento: 309,unidadIngrediente: 'Kg',precioIngrediente: 926)
	FormulasProducto.create(skuProducto: 10,nombreProducto: 'Pan Marraqueta',lote: 900,unidadProducto: 'Kg',skuIngrediente: 4,nombreIngrediente: 'Aceite de Maravilla',requerimiento: 100,unidadIngrediente: 'Lts',precioIngrediente: 3112)
	FormulasProducto.create(skuProducto: 10,nombreProducto: 'Pan Marraqueta',lote: 900,unidadProducto: 'Kg',skuIngrediente: 27,nombreIngrediente: 'Levadura',requerimiento: 279,unidadIngrediente: 'Kg',precioIngrediente: 1376)
	FormulasProducto.create(skuProducto: 11,nombreProducto: 'Margarina ',lote: 900,unidadProducto: 'Kg',skuIngrediente: 4,nombreIngrediente: 'Aceite de Maravilla',requerimiento: 828,unidadIngrediente: 'Lts',precioIngrediente: 3112)
	FormulasProducto.create(skuProducto: 12,nombreProducto: 'Cereal Avena ',lote: 400,unidadProducto: 'Kg',skuIngrediente: 25,nombreIngrediente: 'Azúcar',requerimiento: 133,unidadIngrediente: 'Kg',precioIngrediente: 1016)
	FormulasProducto.create(skuProducto: 12,nombreProducto: 'Cereal Avena ',lote: 400,unidadProducto: 'Kg',skuIngrediente: 20,nombreIngrediente: 'Cacao',requerimiento: 147,unidadIngrediente: 'Kg',precioIngrediente: 1612)
	FormulasProducto.create(skuProducto: 12,nombreProducto: 'Cereal Avena ',lote: 400,unidadProducto: 'Kg',skuIngrediente: 15,nombreIngrediente: 'Avena',requerimiento: 113,unidadIngrediente: 'Kg',precioIngrediente: 1182)
	FormulasProducto.create(skuProducto: 16,nombreProducto: 'Pasta de Trigo ',lote: 1000,unidadProducto: 'Kg',skuIngrediente: 23,nombreIngrediente: 'Harina',requerimiento: 330,unidadIngrediente: 'Kg',precioIngrediente: 4294)
	FormulasProducto.create(skuProducto: 16,nombreProducto: 'Pasta de Trigo ',lote: 1000,unidadProducto: 'Kg',skuIngrediente: 26,nombreIngrediente: 'Sal',requerimiento: 313,unidadIngrediente: 'Kg',precioIngrediente: 926)
	FormulasProducto.create(skuProducto: 16,nombreProducto: 'Pasta de Trigo ',lote: 1000,unidadProducto: 'Kg',skuIngrediente: 2,nombreIngrediente: 'Huevo',requerimiento: 383,unidadIngrediente: 'Un',precioIngrediente: 718)
	FormulasProducto.create(skuProducto: 17,nombreProducto: 'Cereal Arroz ',lote: 1000,unidadProducto: 'Kg',skuIngrediente: 25,nombreIngrediente: 'Azúcar',requerimiento: 360,unidadIngrediente: 'Kg',precioIngrediente: 1016)
	FormulasProducto.create(skuProducto: 17,nombreProducto: 'Cereal Arroz ',lote: 1000,unidadProducto: 'Kg',skuIngrediente: 20,nombreIngrediente: 'Cacao',requerimiento: 350,unidadIngrediente: 'Kg',precioIngrediente: 1612)
	FormulasProducto.create(skuProducto: 17,nombreProducto: 'Cereal Arroz ',lote: 1000,unidadProducto: 'Kg',skuIngrediente: 13,nombreIngrediente: 'Arroz',requerimiento: 290,unidadIngrediente: 'Kg',precioIngrediente: 1504)
	FormulasProducto.create(skuProducto: 18,nombreProducto: 'Pastel ',lote: 200,unidadProducto: 'Un',skuIngrediente: 23,nombreIngrediente: 'Harina',requerimiento: 72,unidadIngrediente: 'Kg',precioIngrediente: 4294)
	FormulasProducto.create(skuProducto: 18,nombreProducto: 'Pastel ',lote: 200,unidadProducto: 'Un',skuIngrediente: 2,nombreIngrediente: 'Huevo',requerimiento: 71,unidadIngrediente: 'Un',precioIngrediente: 718)
	FormulasProducto.create(skuProducto: 18,nombreProducto: 'Pastel ',lote: 200,unidadProducto: 'Un',skuIngrediente: 7,nombreIngrediente: 'Leche',requerimiento: 67,unidadIngrediente: 'Lts',precioIngrediente: 1307)
	FormulasProducto.create(skuProducto: 22,nombreProducto: 'Mantequilla ',lote: 400,unidadProducto: 'Kg',skuIngrediente: 6,nombreIngrediente: 'Crema',requerimiento: 380,unidadIngrediente: 'Lts',precioIngrediente: 9678)
	FormulasProducto.create(skuProducto: 23,nombreProducto: 'Harina',lote: 300,unidadProducto: 'Kg',skuIngrediente: 8,nombreIngrediente: 'Trigo',requerimiento: 309,unidadIngrediente: 'Kg',precioIngrediente: 1601)
	FormulasProducto.create(skuProducto: 24,nombreProducto: 'Tela de Seda ',lote: 400,unidadProducto: 'Mts',skuIngrediente: 33,nombreIngrediente: 'Seda',requerimiento: 444,unidadIngrediente: 'Kg',precioIngrediente: 992)
	FormulasProducto.create(skuProducto: 28,nombreProducto: 'Tela de Lino ',lote: 500,unidadProducto: 'Mts',skuIngrediente: 37,nombreIngrediente: 'Lino',requerimiento: 440,unidadIngrediente: 'Mts',precioIngrediente: 916)
	FormulasProducto.create(skuProducto: 29,nombreProducto: 'Tela de Lana ',lote: 400,unidadProducto: 'Mts',skuIngrediente: 31,nombreIngrediente: 'Lana',requerimiento: 368,unidadIngrediente: 'Mts',precioIngrediente: 1763)
	FormulasProducto.create(skuProducto: 30,nombreProducto: 'Tela de Algodón ',lote: 500,unidadProducto: 'Mts',skuIngrediente: 21,nombreIngrediente: 'Algodón',requerimiento: 460,unidadIngrediente: 'Kg',precioIngrediente: 1462)
	FormulasProducto.create(skuProducto: 34,nombreProducto: 'Cerveza ',lote: 700,unidadProducto: 'Lts',skuIngrediente: 14,nombreIngrediente: 'Cebada',requerimiento: 333,unidadIngrediente: 'Kg',precioIngrediente: 932)
	FormulasProducto.create(skuProducto: 34,nombreProducto: 'Cerveza ',lote: 700,unidadProducto: 'Lts',skuIngrediente: 27,nombreIngrediente: 'Levadura',requerimiento: 319,unidadIngrediente: 'Kg',precioIngrediente: 1376)
	FormulasProducto.create(skuProducto: 35,nombreProducto: 'Tequila ',lote: 500,unidadProducto: 'Lts',skuIngrediente: 44,nombreIngrediente: 'Agave',requerimiento: 430,unidadIngrediente: 'Kg',precioIngrediente: 1254)
	FormulasProducto.create(skuProducto: 36,nombreProducto: 'Papel ',lote: 100,unidadProducto: 'Mts',skuIngrediente: 45,nombreIngrediente: 'Celulosa',requerimiento: 89,unidadIngrediente: 'Kg',precioIngrediente: 1695)
	FormulasProducto.create(skuProducto: 40,nombreProducto: 'Queso ',lote: 900,unidadProducto: 'Kg',skuIngrediente: 7,nombreIngrediente: 'Leche',requerimiento: 1000,unidadIngrediente: 'Lts',precioIngrediente: 1307)
	FormulasProducto.create(skuProducto: 40,nombreProducto: 'Queso ',lote: 900,unidadProducto: 'Kg',skuIngrediente: 41,nombreIngrediente: 'Suero de Leche',requerimiento: 800,unidadIngrediente: 'Lts',precioIngrediente: 3148)
	FormulasProducto.create(skuProducto: 41,nombreProducto: 'Suero de Leche',lote: 200,unidadProducto: 'Lts',skuIngrediente: 7,nombreIngrediente: 'Leche',requerimiento: 2000,unidadIngrediente: 'Lts',precioIngrediente: 1307)
	FormulasProducto.create(skuProducto: 42,nombreProducto: 'Cereal Maíz',lote: 200,unidadProducto: 'Kg',skuIngrediente: 25,nombreIngrediente: 'Azúcar',requerimiento: 67,unidadIngrediente: 'Kg',precioIngrediente: 1016)
	FormulasProducto.create(skuProducto: 42,nombreProducto: 'Cereal Maíz',lote: 200,unidadProducto: 'Kg',skuIngrediente: 20,nombreIngrediente: 'Cacao',requerimiento: 71,unidadIngrediente: 'Kg',precioIngrediente: 1612)
	FormulasProducto.create(skuProducto: 42,nombreProducto: 'Cereal Maíz',lote: 200,unidadProducto: 'Kg',skuIngrediente: 3,nombreIngrediente: 'Maíz',requerimiento: 69,unidadIngrediente: 'Kg',precioIngrediente: 1805)
	FormulasProducto.create(skuProducto: 46,nombreProducto: 'Chocolate',lote: 800,unidadProducto: 'Kg',skuIngrediente: 20,nombreIngrediente: 'Cacao',requerimiento: 296,unidadIngrediente: 'Kg',precioIngrediente: 1612)
	FormulasProducto.create(skuProducto: 46,nombreProducto: 'Chocolate',lote: 800,unidadProducto: 'Kg',skuIngrediente: 25,nombreIngrediente: 'Azúcar',requerimiento: 269,unidadIngrediente: 'Kg',precioIngrediente: 1016)
	FormulasProducto.create(skuProducto: 46,nombreProducto: 'Chocolate',lote: 800,unidadProducto: 'Kg',skuIngrediente: 7,nombreIngrediente: 'Leche',requerimiento: 251,unidadIngrediente: 'Lts',precioIngrediente: 1307)
	FormulasProducto.create(skuProducto: 47,nombreProducto: 'Vino ',lote: 1000,unidadProducto: 'Lts',skuIngrediente: 39,nombreIngrediente: 'Uva',requerimiento: 495,unidadIngrediente: 'Kg',precioIngrediente: 1217)
	FormulasProducto.create(skuProducto: 47,nombreProducto: 'Vino ',lote: 1000,unidadProducto: 'Lts',skuIngrediente: 27,nombreIngrediente: 'Levadura',requerimiento: 570,unidadIngrediente: 'Kg',precioIngrediente: 1376)
	FormulasProducto.create(skuProducto: 47,nombreProducto: 'Vino ',lote: 1000,unidadProducto: 'Lts',skuIngrediente: 25,nombreIngrediente: 'Azúcar',requerimiento: 1000,unidadIngrediente: 'Kg',precioIngrediente: 1016)
	FormulasProducto.create(skuProducto: 48,nombreProducto: 'Pasta de Sémola ',lote: 500,unidadProducto: 'Kg',skuIngrediente: 19,nombreIngrediente: 'Sémola',requerimiento: 160,unidadIngrediente: 'Kg',precioIngrediente: 1613)
	FormulasProducto.create(skuProducto: 48,nombreProducto: 'Pasta de Sémola ',lote: 500,unidadProducto: 'Kg',skuIngrediente: 26,nombreIngrediente: 'Sal',requerimiento: 172,unidadIngrediente: 'Kg',precioIngrediente: 926)
	FormulasProducto.create(skuProducto: 48,nombreProducto: 'Pasta de Sémola ',lote: 500,unidadProducto: 'Kg',skuIngrediente: 2,nombreIngrediente: 'Huevo',requerimiento: 155,unidadIngrediente: 'Un',precioIngrediente: 718)
	FormulasProducto.create(skuProducto: 49,nombreProducto: 'Leche Descremada',lote: 200,unidadProducto: 'Lts',skuIngrediente: 7,nombreIngrediente: 'Leche',requerimiento: 222,unidadIngrediente: 'Lts',precioIngrediente: 1307)
	FormulasProducto.create(skuProducto: 50,nombreProducto: 'Arroz con Leche',lote: 350,unidadProducto: 'Kg',skuIngrediente: 7,nombreIngrediente: 'Leche',requerimiento: 200,unidadIngrediente: 'Lts',precioIngrediente: 1307)
	FormulasProducto.create(skuProducto: 50,nombreProducto: 'Arroz con Leche',lote: 350,unidadProducto: 'Kg',skuIngrediente: 25,nombreIngrediente: 'Azúcar',requerimiento: 41,unidadIngrediente: 'Kg',precioIngrediente: 1016)
	FormulasProducto.create(skuProducto: 50,nombreProducto: 'Arroz con Leche',lote: 350,unidadProducto: 'Kg',skuIngrediente: 13,nombreIngrediente: 'Arroz',requerimiento: 100,unidadIngrediente: 'Kg',precioIngrediente: 1504)
	FormulasProducto.create(skuProducto: 51,nombreProducto: 'Pan Hallulla',lote: 600,unidadProducto: 'Kg',skuIngrediente: 23,nombreIngrediente: 'Harina',requerimiento: 800,unidadIngrediente: 'Kg',precioIngrediente: 4294)
	FormulasProducto.create(skuProducto: 51,nombreProducto: 'Pan Hallulla',lote: 600,unidadProducto: 'Kg',skuIngrediente: 26,nombreIngrediente: 'Sal',requerimiento: 182,unidadIngrediente: 'Kg',precioIngrediente: 926)
	FormulasProducto.create(skuProducto: 51,nombreProducto: 'Pan Hallulla',lote: 600,unidadProducto: 'Kg',skuIngrediente: 22,nombreIngrediente: 'Mantequilla ',requerimiento: 200,unidadIngrediente: 'Kg',precioIngrediente: 12725)
	FormulasProducto.create(skuProducto: 51,nombreProducto: 'Pan Hallulla',lote: 600,unidadProducto: 'Kg',skuIngrediente: 27,nombreIngrediente: 'Levadura',requerimiento: 279,unidadIngrediente: 'Kg',precioIngrediente: 1376)
	FormulasProducto.create(skuProducto: 53,nombreProducto: 'Pan Integral',lote: 620,unidadProducto: 'Kg',skuIngrediente: 52,nombreIngrediente: 'Harina Integral',requerimiento: 500,unidadIngrediente: 'Kg',precioIngrediente: 1949)
	FormulasProducto.create(skuProducto: 53,nombreProducto: 'Pan Integral',lote: 620,unidadProducto: 'Kg',skuIngrediente: 26,nombreIngrediente: 'Sal',requerimiento: 63,unidadIngrediente: 'Kg',precioIngrediente: 926)
	FormulasProducto.create(skuProducto: 53,nombreProducto: 'Pan Integral',lote: 620,unidadProducto: 'Kg',skuIngrediente: 38,nombreIngrediente: 'Semillas Maravilla',requerimiento: 250,unidadIngrediente: 'Kg',precioIngrediente: 1513)
	FormulasProducto.create(skuProducto: 53,nombreProducto: 'Pan Integral',lote: 620,unidadProducto: 'Kg',skuIngrediente: 7,nombreIngrediente: 'Leche',requerimiento: 651,unidadIngrediente: 'Lts',precioIngrediente: 1307)
	FormulasProducto.create(skuProducto: 54,nombreProducto: 'Hamburguesas',lote: 1800,unidadProducto: 'Kg',skuIngrediente: 9,nombreIngrediente: 'Carne',requerimiento: 2154,unidadIngrediente: 'Kg',precioIngrediente: 1704)
	FormulasProducto.create(skuProducto: 54,nombreProducto: 'Hamburguesas',lote: 1800,unidadProducto: 'Kg',skuIngrediente: 26,nombreIngrediente: 'Sal',requerimiento: 153,unidadIngrediente: 'Kg',precioIngrediente: 926)
	FormulasProducto.create(skuProducto: 55,nombreProducto: 'Galletas Integrales',lote: 950,unidadProducto: 'Kg',skuIngrediente: 52,nombreIngrediente: 'Harina Integral',requerimiento: 1365,unidadIngrediente: 'Kg',precioIngrediente: 1949)
	FormulasProducto.create(skuProducto: 55,nombreProducto: 'Galletas Integrales',lote: 950,unidadProducto: 'Kg',skuIngrediente: 20,nombreIngrediente: 'Cacao',requerimiento: 96,unidadIngrediente: 'Kg',precioIngrediente: 1612)
	FormulasProducto.create(skuProducto: 55,nombreProducto: 'Galletas Integrales',lote: 950,unidadProducto: 'Kg',skuIngrediente: 2,nombreIngrediente: 'Huevo',requerimiento: 560,unidadIngrediente: 'Un',precioIngrediente: 718)
	FormulasProducto.create(skuProducto: 56,nombreProducto: 'Hamburguesas de Pollo',lote: 620,unidadProducto: 'Kg',skuIngrediente: 1,nombreIngrediente: 'Pollo',requerimiento: 935,unidadIngrediente: 'Kg',precioIngrediente: 1159)
	FormulasProducto.create(skuProducto: 56,nombreProducto: 'Hamburguesas de Pollo',lote: 620,unidadProducto: 'Kg',skuIngrediente: 26,nombreIngrediente: 'Sal',requerimiento: 65,unidadIngrediente: 'Kg',precioIngrediente: 926)

	PreciosProducto.create(sku: 1,nombre: 'Pollo',precio: 1)
	PreciosProducto.create(sku: 2,nombre: 'Huevo',precio: 2)
	PreciosProducto.create(sku: 3,nombre: 'Maíz',precio: 3)
	PreciosProducto.create(sku: 4,nombre: 'Aceite de Maravilla',precio: 4)
	PreciosProducto.create(sku: 5,nombre: 'Yogur ',precio: 5)
	PreciosProducto.create(sku: 6,nombre: 'Crema',precio: 6)
	PreciosProducto.create(sku: 7,nombre: 'Leche',precio: 7)
	PreciosProducto.create(sku: 8,nombre: 'Trigo',precio: 8)
	PreciosProducto.create(sku: 9,nombre: 'Carne',precio: 9)
	PreciosProducto.create(sku: 10,nombre: 'Pan Marraqueta',precio: 10)
	PreciosProducto.create(sku: 11,nombre: 'Margarina ',precio: 11)
	PreciosProducto.create(sku: 12,nombre: 'Cereal Avena ',precio: 12)
	PreciosProducto.create(sku: 13,nombre: 'Arroz',precio: 13)
	PreciosProducto.create(sku: 14,nombre: 'Cebada',precio: 14)
	PreciosProducto.create(sku: 15,nombre: 'Avena',precio: 15)
	PreciosProducto.create(sku: 16,nombre: 'Pasta de Trigo ',precio: 16)
	PreciosProducto.create(sku: 17,nombre: 'Cereal Arroz ',precio: 17)
	PreciosProducto.create(sku: 18,nombre: 'Pastel ',precio: 18)
	PreciosProducto.create(sku: 19,nombre: 'Sémola',precio: 19)
	PreciosProducto.create(sku: 20,nombre: 'Cacao',precio: 20)
	PreciosProducto.create(sku: 21,nombre: 'Algodón',precio: 21)
	PreciosProducto.create(sku: 22,nombre: 'Mantequilla ',precio: 22)
	PreciosProducto.create(sku: 23,nombre: 'Harina',precio: 23)
	PreciosProducto.create(sku: 24,nombre: 'Tela de Seda ',precio: 24)
	PreciosProducto.create(sku: 25,nombre: 'Azúcar',precio: 25)
	PreciosProducto.create(sku: 26,nombre: 'Sal',precio: 26)
	PreciosProducto.create(sku: 27,nombre: 'Levadura',precio: 27)
	PreciosProducto.create(sku: 28,nombre: 'Tela de Lino ',precio: 28)
	PreciosProducto.create(sku: 29,nombre: 'Tela de Lana ',precio: 29)
	PreciosProducto.create(sku: 30,nombre: 'Tela de Algodón ',precio: 30)
	PreciosProducto.create(sku: 31,nombre: 'Lana',precio: 31)
	PreciosProducto.create(sku: 32,nombre: 'Cuero',precio: 32)
	PreciosProducto.create(sku: 33,nombre: 'Seda',precio: 33)
	PreciosProducto.create(sku: 34,nombre: 'Cerveza ',precio: 34)
	PreciosProducto.create(sku: 35,nombre: 'Tequila ',precio: 35)
	PreciosProducto.create(sku: 36,nombre: 'Papel ',precio: 36)
	PreciosProducto.create(sku: 37,nombre: 'Lino',precio: 37)
	PreciosProducto.create(sku: 38,nombre: 'Semillas Maravilla',precio: 38)
	PreciosProducto.create(sku: 39,nombre: 'Uva',precio: 39)
	PreciosProducto.create(sku: 40,nombre: 'Queso ',precio: 40)
	PreciosProducto.create(sku: 41,nombre: 'Suero de Leche',precio: 41)
	PreciosProducto.create(sku: 42,nombre: 'Cereal Maíz',precio: 42)
	PreciosProducto.create(sku: 43,nombre: 'Madera',precio: 43)
	PreciosProducto.create(sku: 44,nombre: 'Agave',precio: 44)
	PreciosProducto.create(sku: 45,nombre: 'Celulosa',precio: 45)
	PreciosProducto.create(sku: 46,nombre: 'Chocolate',precio: 46)
	PreciosProducto.create(sku: 47,nombre: 'Vino ',precio: 47)
	PreciosProducto.create(sku: 48,nombre: 'Pasta de Sémola ',precio: 48)
	PreciosProducto.create(sku: 49,nombre: 'Leche Descremada',precio: 49)
	PreciosProducto.create(sku: 50,nombre: 'Arroz con Leche',precio: 50)
	PreciosProducto.create(sku: 51,nombre: 'Pan Hallulla',precio: 51)
	PreciosProducto.create(sku: 52,nombre: 'Harina Integral',precio: 52)
	PreciosProducto.create(sku: 53,nombre: 'Pan Integral',precio: 53)
	PreciosProducto.create(sku: 54,nombre: 'Hamburguesas',precio: 54)
	PreciosProducto.create(sku: 55,nombre: 'Galletas Integrales',precio: 55)
	PreciosProducto.create(sku: 56,nombre: 'Hamburguesas de Pollo',precio: 56)
